<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MediatR" Version="14.0.0" />
		<PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="9.0.11" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\PartyService.Application\PartyService.Application.csproj" />
		<ProjectReference Include="..\PartyService.Infrastructure\PartyService.Infrastructure.csproj" />
	</ItemGroup>
</Project>